#!/bin/sh

# ccache-clang
CUR_DIR=$(dirname $0)
CCACHE_EXEC_DIR=$CUR_DIR/../../../build
export CCACHE_CONFIG=$CUR_DIR/../../config.yaml
export PATH=$CCACHE_EXEC_DIR:$PATH
env

# /usr/bin/clang "$@"
ccache /usr/bin/clang "$@"